version: 2

jobs:
  deploy:
    docker:
      - image: circleci/node:8-browsers
      branches:
        only:
          - master
      steps:
        - run:
            name: Deploy to Firebase
            command: npx firebase deploy --token=$FIREBASE_TOKEN --non-interactive
  build:
    docker:
        - image: circleci/node:8-browsers
    branches:
      only:
        - master
    steps:
      - checkout
      - run:
          command:  |
            mkdir ~/.npm-global
            npm config set prefix '~/.npm-global'
            export PATH=~/.npm-global/bin:$PATH
      - restore_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install --silent --no-audit && sudo npm install -g tslint typescript
      - save_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - run: npm run test:cli
      - run: npm run build:prod

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - deploy
