version: 2

jobs:
  build:
    docker:
        - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install --silent
      - save_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - run: xvfb-run -a npm run build:prod
      - run: cp dist docs
      - persist_to_workspace:
          root: .
          paths: docs

  tests:
    docker:
        - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install --silent
      - save_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - run: xvfb-run -a npm run test:cli

workflows:
  version: 2
  default_workflow:
    jobs:
      - build:
          filters:
              branches:
                  ignore:
                    - gh-pages
      - tests:
          requires:
            - build
