version: 2

jobs:
  build:
    docker:
        - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install --silent
      - save_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - run: xvfb-run -a npm run build:prod
      - run: cp -r dist docs
      - persist_to_workspace:
          root: .
          paths: docs

  tests:
    docker:
        - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install --silent
      - save_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - run: xvfb-run -a npm run test:cli

  gh-pages-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: docs
      - add_ssh_keys:
          fingerprints:
            - "ab:54:38:1a:42:d1:27:d0:eb:a7:f4:de:dc:15:38:c3"
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "circleci@circleci.com"
            git config user.name "circleci"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dist .

workflows:
  version: 2
  default_workflow:
    jobs:
      - build:
          filters:
              branches:
                  ignore:
                    - gh-pages
      - tests:
          requires:
            - build
      - gh-pages-deploy:
          requires:
            - tests
