version: 2

jobs:
  build:
    docker:
        - image: circleci/node:8-browsers
    branches:
      only:
        - master
    steps:
      - checkout
      - run:
          command:  |
            mkdir ~/.npm-global
            npm config set prefix '~/.npm-global'
            export PATH=~/.npm-global/bin:$PATH
      - restore_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install --silent --no-audit && sudo npm install -g tslint typescript
      - save_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - run: npm run test:cli
      - run: npm run build:prod

      # Deploy to Firebase
      - run: export PATH="$PATH:~/workspace/node_modules/.bin"

      - run:
          name: Deploy to Firebase
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN --non-interactive

workflows:
  version: 2
  default_workflow:
    jobs:
      - build
