version: 2

jobs:
  build:
    docker:
        - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install --silent --no-audit
      - save_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - run: npm run build:prod

      # Allow reusing the already built code in future jobs
      - run: cp -r dist docs
      - persist_to_workspace:
          root: .
          paths: dist

  tests:
    docker:
        - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install --silent --no-audit
      - save_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - run: npm run test:cli

  deploy:
    docker:
      - image: node:8.10.0
    working_directory: ~/project
    steps:
      - checkout
      - attach_workspace:
          at: ~/workspace
      - run: cp -R ~/workspace/dist ~/project/dist
      - run: ls ~/project/dist
      - restore_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install --silent --no-audit
      - save_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - run:
          name: Deploy to Firebase
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN --non-interactive

workflows:
  version: 2
  default_workflow:
    jobs:
      - build:
          filters:
              branches:
                  ignore:
                    - gh-pages
      - tests:
          requires:
            - build
      - deploy:
          filters:
              branches:
                only:
                  - master
          requires:
            - build
            - tests
