name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install TypeScript and Firebase Tools
      run: sudo npm install -g tslint typescript firebase-tools
    - name: Install dependencies
      run: npm install --silent --no-audit
    - name: Tests
      run: npm run test:cli
    - name: Production build
      run: npm run build:prod
